feat: Add occurrence iterator
lsndr/rrule-rust pull request #36
Opened 2023-12-31 01:02 UTC by tomquist

2024-01-04 06:16 UTC, lsndr requested changes

2024-01-04 06:16 UTC, lsndr commented on src/lib.rs
> +  pub fn occurrences(&self, this: Reference<JsRRuleSet>, env: Env) -> napi::Result<Occurrences> {
Please add test for this method

2024-01-07 17:58 UTC, tomquist commented on src/lib.rs
> +  pub fn occurrences(&self, this: Reference<JsRRuleSet>, env: Env) -> napi::Result<Occurrences> {
Done

2024-01-09 03:40 UTC, lsndr approved these changes

2024-01-09 03:40 UTC, merged